const root=document.documentElement;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
document.querySelectorAll('.theme-toggle').forEach(toggle=>toggle.remove());
root.classList.remove('light');
const header=document.querySelector('.site-header');const progress=document.querySelector('.scroll-progress');const backTop=document.querySelector('.back-top');
document.querySelectorAll('.desktop-nav a,.mobile-nav a').forEach(link=>{if(link.textContent.trim().toLowerCase()==='book a repair')link.remove()});
const socialUrls={instagram:'https://www.instagram.com/_ifixon/?hl=en',youtube:'https://www.youtube.com/@IFIXON',telegram:'https://t.me/'};Object.entries(socialUrls).forEach(([name,url])=>{document.querySelectorAll(`.social-link.${name}, .footer-links a`).forEach(link=>{if(link.textContent.trim().toLowerCase().startsWith(name)){link.href=url;link.target='_blank';link.rel='noreferrer'}})});
const serviceBreadcrumb=document.querySelector('.service-page .service-breadcrumb');if(serviceBreadcrumb&&!serviceBreadcrumb.querySelector('.back-to-repairs')){const backLink=document.createElement('a');backLink.className='back-to-repairs';backLink.href='index.html#services';backLink.innerHTML='<span aria-hidden="true">←</span> Back to repairs';serviceBreadcrumb.prepend(backLink)}
function updateScroll(){const scrollable=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=`${scrollable>0?(scrollY/scrollable)*100:0}%`;header?.classList.toggle('scrolled',scrollY>40);backTop?.classList.toggle('visible',scrollY>500)}addEventListener('scroll',updateScroll,{passive:true});updateScroll();
const menuToggle=document.querySelector('.menu-toggle');const mobileNav=document.querySelector('.mobile-nav');
menuToggle?.addEventListener('click',()=>{const open=menuToggle.getAttribute('aria-expanded')==='true';menuToggle.setAttribute('aria-expanded',String(!open));mobileNav.classList.toggle('open',!open)});mobileNav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menuToggle.setAttribute('aria-expanded','false');mobileNav.classList.remove('open')}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(element=>revealObserver.observe(element));
const counterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const counter=entry.target;const target=Number(counter.dataset.target);const duration=reducedMotion?1:1300;const started=performance.now();function tick(now){const progress=Math.min((now-started)/duration,1);counter.textContent=Math.floor((1-Math.pow(1-progress,3))*target);if(progress<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);counterObserver.unobserve(counter)}),{threshold:.7});document.querySelectorAll('.counter').forEach(counter=>counterObserver.observe(counter));
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{const hash=link.getAttribute('href');if(hash==='#top'){event.preventDefault();window.scrollTo({top:0,left:0,behavior:reducedMotion?'auto':'smooth'});return}const target=document.querySelector(hash);if(target){event.preventDefault();window.scrollTo({top:Math.max(0,target.offsetTop-24),left:0,behavior:reducedMotion?'auto':'smooth'})}}));
document.querySelectorAll('.magnetic').forEach(button=>{button.addEventListener('mousemove',event=>{if(reducedMotion)return;const box=button.getBoundingClientRect();button.style.transform=`translate(${(event.clientX-box.left-box.width/2)*.12}px,${(event.clientY-box.top-box.height/2)*.18-3}px)`});button.addEventListener('mouseleave',()=>button.style.transform='')});
const glow=document.querySelector('.cursor-glow');addEventListener('pointermove',event=>{if(glow&&!reducedMotion){glow.style.left=`${event.clientX}px`;glow.style.top=`${event.clientY}px`}});
const slides=[...document.querySelectorAll('.testimonial')];const dots=[...document.querySelectorAll('.carousel-dots button')];let slideIndex=0;function showSlide(index){slideIndex=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.classList.toggle('active',i===slideIndex));dots.forEach((dot,i)=>dot.classList.toggle('active',i===slideIndex))}document.querySelector('.prev')?.addEventListener('click',()=>showSlide(slideIndex-1));document.querySelector('.next')?.addEventListener('click',()=>showSlide(slideIndex+1));dots.forEach((dot,i)=>dot.addEventListener('click',()=>showSlide(i)));if(!reducedMotion&&slides.length>1)setInterval(()=>showSlide(slideIndex+1),7000);
document.querySelectorAll('.faq-list details').forEach(detail=>detail.addEventListener('toggle',()=>{if(detail.open)document.querySelectorAll('.faq-list details').forEach(other=>{if(other!==detail)other.removeAttribute('open')})}));
const form=document.querySelector('.booking-form');const whatsappNumber='917200072526';form?.addEventListener('submit',event=>{event.preventDefault();if(!form.checkValidity()){form.classList.add('invalid');form.querySelector(':invalid')?.focus();return}form.classList.remove('invalid');const data=new FormData(form);const message=['Hello IFIXON, I would like to book a repair.','Name: '+data.get('name'),'Phone: '+data.get('phone'),'Email: '+data.get('email'),'Device: '+data.get('device'),'Repair: '+data.get('repair'),'Preferred date: '+data.get('date'),'Preferred time: '+data.get('time'),'Address: '+data.get('address'),data.get('message')?'Message: '+data.get('message'):''].filter(Boolean).join('\n');form.reset();setTimeout(()=>{window.open('https://wa.me/'+whatsappNumber+'?text='+encodeURIComponent(message),'_blank','noopener,noreferrer')},350)});
